# Book settings
title: Learning from data
author: Christian Forssén
email: christian.forssen@chalmers.se
logo: ./fig/logo.png
description: >- # this means to ignore newlines
  This book comprises the lecture notes for the course TIF285/FIM285
  Learning from data taught at Chalmers University of Technology 
  and Gothenburg University.

execute:
  execute_notebooks         : cache  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""    # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []    # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)
  timeout                   : 30    # The maximum time (in seconds) each notebook cell is allowed to run.
  run_in_temp               : false # If `True`, then a temporary directory will be created and used as the command working directory (cwd),
                                    # otherwise the notebook's parent directory will be the cwd.
  allow_errors              : false # If `False`, when a code cell raises an error the execution is stopped, otherwise all cells are always run.
  stderr_output             : show  # One of 'show', 'remove', 'remove-warn', 'warn', 'error', 'severe'

#######################################################################################
# LaTeX-specific settings
latex:
  latex_engine: xelatex             # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

bibtex_reference_style:
  - author_year

#######################################################################################
# Information about where the book exists on the web
repository:
  url                       : https://github.com/physics-chalmers/tif285  # The URL to your book's repository
  path_to_book              : "./doc/LectureNotes"  # A path to your book's folder, relative to the repository root.
  branch                    : master  # Which branch of the repository should be used when creating links

#######################################################################################
# HTML-specific settings
# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  comments:
    hypothesis              : false
    utterances              : 
      repo: "https://github.com/physics-chalmers/tif285" # Allows to write comments that turns into git issues using utterances. See https://jupyterbook.org/en/stable/interactive/comments/utterances.html
#  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
#  baseurl                   : ""  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/    

#######################################################################################
# Customize LaTeX via Sphinx
# see also https://www.sphinx-doc.org/en/master/latex.html

# old settings...
#sphinx:
#  config:
#    bibtex_reference_style: label
#    bibtex_default_style: 'alpha'  
#    # By default MathJax version 2 is currently used. If you are using a lot of math, you may want to try using version 3, which claims to improve load speeds by 60 - 80%:  
#    #mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@2/MathJax.js?config=TeX-AMS-MML_HTMLorMML
#    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#    #myst_override_mathjax: true
 
# from tif385   
sphinx:
  config:
    nb_custom_formats:
      .Rmd:
        - jupytext.reads
        - fmt: Rmd
    # https://jupyterbook.org/advanced/pdf.html#pdf-latex
    #CF removed. Tope level is chapter.
    #latex_toplevel_sectioning: 'part'
    # TODO: #917 this path will be the default in sphinx v4
    # mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    # However, it is incompatible with the mathjax config below for macros
    mathjax3_config:
      TeX:
        Macros:
          "N": "\\mathbb{N}"
          "floor": ["\\lfloor#1\\rfloor", 1]
          "bmat": ["\\left[\\begin{array}"]
          "emat": ["\\end{array}\\right]"]
    latex_elements:
        preamble: |
          \newcommand\N{\mathbb{N}}
          \newcommand\floor[1]{\lfloor#1\rfloor}
          \newcommand{\bmat}{\left[\begin{array}}
          \newcommand{\emat}{\end{array}\right]}
          \renewcommand{\vec}[1]{\boldsymbol{#1}}

#######################################################################################
# Parse and render settings
parse:
  myst_url_schemes          : [mailto, http, https]  # URI schemes that will be recognised as external URLs in Markdown links
  myst_enable_extensions    : ["dollarmath", "amsmath","html_image"]


#######################################################################################
# Launch button settings
launch_buttons:
  #colab_url                 : "https://colab.research.google.com"
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  thebe                     : true  # Add a thebe button to pages (requires the repository to run on Binder)
